### ISSUE TITLE
Edit logo on contact page

### ISSUE THREAD

**Issue by kcotto** [griffithlab/dgi-db#493] opened 2020-09-18 16:31 UTC
<img width="1417" alt="Screen Shot 2020-09-18 at 11 30 37 AM" src="https://user-images.githubusercontent.com/22246534/93622255-6e5f9f00-f9a2-11ea-9936-aed3fe42388c.png">
The logo on the contact page should probably be changed/edited to look nicer.

**Comment by susannasiebert** [comment] 2020-09-22 14:28
This is a duplicate of #356. Closing.

**Closed by susannasiebert** 2020-09-22 14:28 UTC
