### ISSUE TITLE
Gene categories don't always show when CIViC is the only source selected

### ISSUE THREAD

**Issue by kcotto** [griffithlab/dgi-db#532] opened 2020-10-01 17:02 UTC
<img width="1059" alt="Screen Shot 2020-10-01 at 11 23 38 AM" src="https://user-images.githubusercontent.com/22246534/94840110-8a6d3280-03dd-11eb-970c-b226d65a379f.png">

This appears to be intermittent though. Sharon and I both see this but Susanna and Adam do not. Something to keep an eye on.

**Comment by susannasiebert** [comment] 2020-10-01 17:28
I was actually testing the wrong thins and can confirm this problem now. It looks like the CIViC updater ran last night and failed (along with a few other ones), resulting in the imported claims not getting grouped.

**Comment by susannasiebert** [comment] 2020-10-01 17:49
This was caused by the CIViC API updater failing. I restored the last data dump so this issue is now fixed. I will make a new PR to address the various updater failures.

**Closed by susannasiebert** 2020-10-01 17:49 UTC
